### ISSUE TITLE
Question 7.4 is missing in the quiz form

### ISSUE THREAD

**Issue by Lah123** [Azure/ADX-in-a-Day-Lab2#28]
The folowing question is present in the lab:
![image](https://github.com/Azure/ADX-in-a-Day-Lab2/assets/29096411/f52d7369-a92d-40ae-8839-9142264040fa)

But not present in the quiz form:
![image](https://github.com/Azure/ADX-in-a-Day-Lab2/assets/29096411/37f5fe60-60c3-4bf1-90f1-861556fb21ad)

I would expect all questions to be in the quiz form. This is quite confusing.

**Comment by hfleitas** [comment]
@Lah123, Good catch, it must of been missed due to required ones vs not required ones. We will fix the quiz. Pls consider 7.4 as not required till then.

**Comment by hfleitas** [comment]
fixed readme, thx
