### ISSUE TITLE
Digital Badge not Issued

### ISSUE THREAD

**Issue by Georgios-Grigoriou** [Azure/ADX-in-a-Day-Lab2#30]
I went through the training submitted the forms for lab 1 and lab 2 it's been more than 5 working days and I haven't received the digital badge 

Is there an issue with the alert ?

Thanks 

Best Regards 
Georgios Grigoriou

**Comment by hfleitas** [comment]
lets use main repo for tracking https://github.com/Azure/ADX-in-a-Day/issues/17
