### ISSUE TITLE
Completion Credly badge 

### ISSUE THREAD

**Issue by spacemc2** [Azure/ADX-in-a-Day-Lab2#31]
I have already finished the two Labs and submitted the completion receipt. I have been waiting for the Credly badge, but I haven't received it yet, could you guys check this for me?
 I would appretiate it, and thanks for your time.

Best,
MTO

**Comment by SuryaTejJosyula** [comment]
Badge is issued to mtorresroadby@gmail.com. Thank you for your patience.
